version: "3"
services:
  go:
    build: ./build # Dockerfileが配置してあるディレクトリを指定
    tty: true # コンテナを起動させ続ける（永続化させる）ために必要な設定
    volumes: # ローカルのファイルとコンテナ内のファイルを同期させている
      - type: bind
        source: "./cmd"
        target: "/go/src/app"
    working_dir: /go/src/app  # コンテナに入った際のデフォルトのディレクトリを指定
                              # これにより、コンテナを立ち上げたコンテナに入った際に
                              # /go/src/appディレクトリから作業を開始することができる